version: '3'

services:
  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    env_file: .env
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
      - ./letsencrypt:/letsencrypt
    networks:
      - proxy
    depends_on:
      - dns-validator

  dns-validator:
    build: ./middleware
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge 